name: Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy (used only for logging; build runs on server)
        default: main
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prep SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT || 22 }}
          request_pty: true
          script_stop: true
          command_timeout: 30m
          script: |
            set -euxo pipefail
            : > ~/.hushlogin || true

            command -v node >/dev/null || { echo "node not found"; exit 1; }
            command -v npm  >/dev/null || { echo "npm not found";  exit 1; }
            command -v git  >/dev/null || { echo "git not found";  exit 1; }
            command -v rsync >/dev/null || { echo "rsync not found"; exit 1; }
            command -v systemctl >/dev/null || { echo "systemctl not found"; exit 1; }

            echo "Requested ref: ${{ github.event.inputs.ref }}"

            # Memory helpers: increase Node's heap and add 2G swap if none exists
            export NODE_OPTIONS="${NODE_OPTIONS:---max_old_space_size=2048}"

            if ! swapon --show | grep -q '^'; then
              echo "No swap detected; creating 2G swapfile to help builds"
              sudo fallocate -l 2G /swapfile || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
              sudo chmod 600 /swapfile
              sudo mkswap /swapfile
              sudo swapon /swapfile
            fi

            cd /srv/app-frontend/frontend

            # Your exact commands with absolute paths for outputs
            git pull
            npm ci --no-audit --no-fund
            npm run build

            sudo rsync -a --delete /srv/app-frontend/frontend/dist/ /var/www/app/
            sudo nginx -t || true
            sudo systemctl reload nginx

            echo "DEPLOY COMMIT: $(git rev-parse --short HEAD)"
