name: Deploy Frontend (scp tar + sudo tar)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Build
        run: |
          set -euxo pipefail
          npm ci
          npm run build
          du -sh dist || true
          tar -C dist -czf dist.tar.gz .

      - name: Upload dist.tar.gz via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT || 22 }}
          source: "dist.tar.gz"
          target: "/tmp/app_dist_${{ github.run_id }}_${{ github.run_attempt }}.tar.gz"
          overwrite: true
          tar_tmp_path: ""     # don't retar; we already tarred

      - name: Unpack to /var/www/app and reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT || 22 }}
          script_stop: true
          command_timeout: 30m
          script: |
            set -euxo pipefail
            : > ~/.hushlogin || true
            TAR="/tmp/app_dist_${{ github.run_id }}_${{ github.run_attempt }}.tar.gz"
            sudo mkdir -p /var/www/app
            echo "Space before deploy:"; df -h /var/www || true
            sudo tar -xzf "$TAR" -C /var/www/app
            sudo rm -f "$TAR"
            echo "Space after deploy:"; df -h /var/www || true
            sudo systemctl reload nginx
