name: Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prep SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_SSH_PORT || 22 }}
          script_stop: true          # fail fast on any error
          request_pty: true          # stream output nicely
          command_timeout: 30m
          script: |
            set -euxo pipefail
            # silence Ubuntu login banner
            : > ~/.hushlogin || true

            # ensure Node is on PATH (supports nvm or system node)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            [ -s "/usr/local/nvm/nvm.sh" ] && . "/usr/local/nvm/nvm.sh"
            command -v nvm >/dev/null && nvm use --silent 20 || true
            export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

            cd /srv/app-frontend/frontend

            # deterministic update & visible commit
            git fetch origin ${{ github.event.inputs.ref || 'main' }}
            git reset --hard origin/${{ github.event.inputs.ref || 'main' }}
            echo "DEPLOY COMMIT: $(git rev-parse --short HEAD)"

            node -v; npm -v
            npm ci
            npm run build

            sudo mkdir -p /var/www/app
            sudo rsync -av --delete dist/ /var/www/app/
            sudo systemctl reload nginx
