name: Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Test with TTY
        run: |
          ssh -t -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" "date; whoami; pwd; echo 'Command completed'"

      - name: Deploy Frontend
        run: |
          ssh -t -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" '
          set -ex
          echo "=== Starting deployment ==="
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          
          echo "=== Checking if frontend directory exists ==="
          if [ ! -d "/srv/app-frontend/frontend" ]; then
            echo "ERROR: Directory /srv/app-frontend/frontend does not exist"
            echo "Available directories in /srv:"
            ls -la /srv/ || echo "Cannot list /srv"
            exit 1
          fi
          
          echo "=== Changing to frontend directory ==="
          cd /srv/app-frontend/frontend
          pwd
          
          echo "=== Git status ==="
          git status
          git log --oneline -5
          
          echo "=== Fetching from origin ==="
          git fetch origin
          
          echo "=== Checkout and reset ==="
          git checkout ${{ github.event.inputs.ref || 'main' }}
          git reset --hard origin/${{ github.event.inputs.ref || 'main' }}
          
          echo "=== Clearing caches ==="
          rm -rf node_modules dist .next .nuxt build
          npm cache clean --force
          
          echo "=== Installing dependencies ==="
          npm ci
          
          echo "=== Building ==="
          npm run build
          
          echo "=== Syncing files ==="
          sudo rsync -av --delete /srv/app-frontend/frontend/dist/ /var/www/app/
          
          echo "=== Reloading nginx ==="
          sudo systemctl reload nginx
          
          echo "=== Deployment completed ==="
          git log --oneline -1
          echo "Deployed commit: $(git rev-parse HEAD)"
          '
