name: Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH Output
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" 'exec 2>&1; date; whoami; pwd; echo "Command completed"'

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" \
            "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" <<'DEPLOY_EOF'
          set -eux  # -e: exit on error, -u: fail on unset vars, -x: show each command

          echo "=== Starting deployment ==="
          echo "User: $(whoami)"
          echo "Dir:  $(pwd)"

          if [ ! -d /srv/app-frontend/frontend ]; then
            echo "Directory /srv/app-frontend/frontend not found"
            ls -la /srv/
            exit 1
          fi

          cd /srv/app-frontend/frontend
          echo "PWD after cd: $(pwd)"

          git fetch origin main
          git reset --hard origin/main
          echo "Commit deployed: $(git rev-parse --short HEAD)"

          node -v || true
          npm -v  || true
          npm ci
          npm run build

          sudo rsync -av --delete dist/ /var/www/app/
          sudo systemctl reload nginx
          echo "=== Deployment complete ==="
          DEPLOY_EOF

