name: Deploy Frontend (quiet rsync)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true

concurrency:
  group: deploy-frontend
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Build
        run: |
          set -euxo pipefail
          npm ci
          npm run build
          test -f dist/index.html

      - name: Deploy via rsync (quiet, non-tty)
        env:
          HOST: ${{ secrets.DROPLET_HOST }}
          USER: ${{ secrets.DROPLET_USER }}
          PORT: ${{ secrets.DROPLET_SSH_PORT || 22 }}
          SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          REMOTE_TMP: /tmp/app_tmp_${{ github.run_id }}_${{ github.run_attempt }}
        run: |
          set -euxo pipefail

          # Write SSH key & known_hosts
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          printf '%s\n' "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts 2>/dev/null || true

          # IMPORTANT: no quotes around ~/.ssh/id_rsa so ~ expands.
          SSH_OPTS="-p $PORT -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o LogLevel=ERROR -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o RequestTTY=no -T"

          # Preflight: ensure remote shell is QUIET (no stray echoes/MOTD).
          # If this prints anything besides __CLEAN__, we abort to protect rsync.
          CLEAN=$(
            ssh $SSH_OPTS "$USER@$HOST" 'set -eu; : > ~/.hushlogin || true; printf "__CLEAN__"'
          )
          if [ "$CLEAN" != "__CLEAN__" ]; then
            echo "Remote login produced unexpected output (likely from ~/.bashrc or MOTD)."
            echo "Please remove any echo/printf in ~/.bashrc (wrap with: [ -n \"$PS1\" ] || return)."
            exit 1
          fi

          # Ensure rsync available and prep temp dir (no sudo/stdio mixing)
          ssh $SSH_OPTS "$USER@$HOST" '
            set -e
            command -v rsync >/dev/null || { sudo apt-get update -y && sudo apt-get install -y rsync; }
            rm -rf "'"$REMOTE_TMP"'"
            mkdir -p "'"$REMOTE_TMP"'"
          '

          # rsync to temp dir — -T (no TTY) and quiet ssh. This avoids protocol noise.
          rsync -az --delete -e "ssh $SSH_OPTS" dist/ "$USER@$HOST:$REMOTE_TMP/"

          # Promote to /var/www/app using sudo rsync (no stdin to sudo)
          ssh $SSH_OPTS "$USER@$HOST" '
            set -euo pipefail
            sudo mkdir -p /var/www/app
            sudo rsync -av --delete "'"$REMOTE_TMP"'"/ /var/www/app/
            rm -rf "'"$REMOTE_TMP"'"
            sudo systemctl reload nginx
          '
