name: Deploy Frontend
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to deploy
        default: main
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_HOST }}" >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" "echo 'SSH connection successful'; whoami; pwd"

      - name: Check if directory exists
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" "ls -la /srv/app-frontend/ || echo 'Directory /srv/app-frontend does not exist'"

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.DROPLET_SSH_PORT || 22 }}" "${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}" '
          set -ex
          echo "=== Starting deployment ==="
          echo "Current user: $(whoami)"
          echo "Current directory: $(pwd)"
          
          echo "=== Checking if frontend directory exists ==="
          if [ ! -d "/srv/app-frontend/frontend" ]; then
            echo "ERROR: Directory /srv/app-frontend/frontend does not exist"
            echo "Available directories in /srv:"
            ls -la /srv/ || echo "Cannot list /srv"
            exit 1
          fi
          
          echo "=== Changing to frontend directory ==="
          cd /srv/app-frontend/frontend
          pwd
          
          echo "=== Git status ==="
          git status || echo "Git status failed"
          git log --oneline -5 || echo "Git log failed"
          
          echo "=== Fetching from origin ==="
          git fetch origin || echo "Git fetch failed"
          
          echo "=== Checkout and reset ==="
          git checkout ${{ github.event.inputs.ref || 'main' }} || echo "Git checkout failed"
          git reset --hard origin/${{ github.event.inputs.ref || 'main' }} || echo "Git reset failed"
          
          echo "=== Clearing caches ==="
          rm -rf node_modules dist .next .nuxt build
          npm cache clean --force || echo "npm cache clean failed"
          
          echo "=== Installing dependencies ==="
          npm ci || echo "npm ci failed"
          
          echo "=== Building ==="
          npm run build || echo "npm run build failed"
          
          echo "=== Deployment completed ==="
          '
